### ISSUE TITLE
Permission Problems

### ISSUE THREAD

**Issue by pdoan017** [igemuottawa/igem-bricklayer#6]
Is there something I have to do to get permission to grab the xml files for the parts?

**Comment by krutkay** [comment]
They should be free for anybody to grab.

If you post your code we'll (or I'll) help you debug it.

**Comment by mef51** [comment]
You cannot make AJAX requests (or any kind of scripted http request) from the browser to websites on another domain.
It's a security risk so servers don't let you: http://en.wikipedia.org/wiki/Cross-origin_resource_sharing

You can however make requests from the server (instead of from a browser), like we do in the file `brickSearchService.coffee`
